<?php
/**
 * "Seo Layered Navigation" extension for "Magento Commerce" by "EcommerceTeam (www.ecommerce-team.com)"
 *
 * @category     Extension
 * @copyright    Copyright (c) 2014 EcommerceTeam (http://www.ecommerce-team.com)
 * @author       EcommerceTeam
 * @version      4.0.0
 */


/** @var $this EcommerceTeam_Sln_Block_Layer_Filter_Attribute */
?>
<ol>
<?php
$i = 0;
$limit = $this->getOptionsLimit();
$count = count($this->getAllItems());
$showMore = $limit && ($count > $limit);
foreach ($this->getAllItems() as $_item): $i++; ?>
    <li
        <?php if ($_item->getLevel() > 0):?>style="padding-left:<?php echo $_item->getLevel() * 15?>px"<?php endif;?>
        <?php if ($showMore && ($i > $limit)):?>class="additional hidden"<?php endif;?>
    >
        <?php if ($_item->getCount() > 0 && !$_item->getIsSelected()): ?>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $_item->getLabel() ?></span>
        <?php endif; ?>
        <?php if (!method_exists($this, 'shouldDisplayProductCount') || $this->shouldDisplayProductCount()): ?>
            (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
    <?php if ($showMore): ?>
        <li class="more">
            <span class="more-label"><?php echo $this->__('Show more')?></span>
            <span class="more-label" style="display:none;"><?php echo $this->__('Show less')?></span>
        </li>
    <?php endif; ?>
</ol>
