<?php
/**
 * Top menu for store
 *
 * @see Queldorei_Navigation_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<!-- navigation BOF -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('custom_navi')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navi_after_tabs')->toHtml() ?>
<!-- navigation EOF -->