<?php
/* to override the default configurable options template  */

//echo ;

include_once 'attributeSwatches.php';
//$_d = $this->getJsonConfig();
$_json_config = addAttributeSwatches($this->getJsonConfig());
$_product = $this->getProduct();

$labelsOptionsArray = array();
foreach ($_product->_data['media_gallery']['images'] as  $_vip1_image){
    if ($_vip1_image['associated_attributes'] && $_vip1_image['associated_attributes'] != ''){
        $labelsOptionsArray [$_vip1_image['associated_attributes']] = $_vip1_image['label'];
    }
}
?>
<?php if ($_product->isSaleable() && count($_json_config["attributes"])): ?>
    <dl id="options-container-<?php echo $_product->getId(); ?>">
        <?php foreach ($_json_config["attributes"] as $_attribute): ?>

            <dt id="label-attribute-<?php echo $_attribute["id"] ?>"><label class="required"><em>*</em><?php echo $_attribute["label"] ?></label><span class="selected-label">&nbsp;</span>   </dt>
            <dd>
                <?php
                /* WILL DISPLAY THE COLOR SWATCHES AND ALL THE CUSTOM OPTION SELECTORS HERE */
                if (in_array($_attribute["swatch_type"], array("image", "child", "label"))) {
                    ?>
                    <div id="attribute-<?php echo $_attribute["id"] ?>-container" class="product-swatches-container">
						<?php if ($_attribute['code'] == 'color' && count($_attribute["options"]) > 0): ?>
                        <ul id="swatches-options-<?php echo $_attribute["id"] ?>" class="has-swatches" <?php /* if ($_attribute["swatch_type"] == "image") echo ' class="has-swatches"'*/ ?>>
                                <?php
                                /* preload swatches from product gallery if necessary */
                                $_gallery_images = array();
                                $_load_swatch_from_gallery = Mage::getStoreConfig("attributeswatches/settings/images") == "gallery";
                                if ($_attribute["swatch_type"] == "child" && $_load_swatch_from_gallery) {
                                    $_gallery = $_product->getSwatchesGalleryImages($_attribute["id"]);
                                    foreach ($_gallery as $_image) {
                                        $_gallery_images[$_image->getAttributeValue()] = $_image->getFile();
                                    }
                                }
                                foreach ($_attribute["options"] as $_option) {
                                    ?>
                                <li>
                                    <?php
                                    switch ($_attribute["swatch_type"]) {
                                        case "child":
                                            $_image = "";
                                            if ($_load_swatch_from_gallery) {
                                                if(isset($_gallery_images[$_option["id"]])){
                                                $_image = $this->helper('catalog/image')->init($_product, 'image', $_gallery_images[$_option["id"]]);
                                                }else{
                                                    $_image = $this->helper('catalog/image')->init($_product, 'image');
                                                }
                                            } else {
                                                $_image_product = Mage::getModel('catalog/product')->load($_option["products"][0]);
                                                $_image = $this->helper('catalog/image')->init($_image_product, 'image');
                                            }
                                            ?>
                                            <a class="" data-label="<?php echo $labelsOptionsArray['attribute'.$_attribute['id'].'-'.$_option["id"]]?>" title="<?php echo $_option["label"] ?>" data-original-title="<?php echo $_option["label"] ?>"  rel="<?php echo $_option["id"] ?>" id="swatches_option_value_<?php echo $_option["id"] ?>" href="<?php echo $_image; ?>" rev="<?php echo $_image->resize(256); ?>">
                                                <?php
                                                echo "<img src='" . $_image->resize(150) . "' title='" . $_option["label"] . "' alt='" . $_option["label"] . "'/>";
                                                ?>
                                            </a>
                                            <span class="tooltip-container"><span class="tooltip"><span><?php echo $_option["label"] ?></span></span></span>
                                            <?php
                                            break;
                                        case 'image':
                                            ?>
                                            <a class="" style="<?php echo $_option["swatch_value"] ?>" data-original-title="<?php echo $_option["label"] ?>"  title="<?php echo $_option["label"] ?>" rel="<?php echo $_option["id"] ?>" id="swatches_option_value_<?php echo $_option["id"] ?>" href="#" rev="">
                                                <span><?php echo $_option["label"] ?></span>
                                            </a>
                                            <span class="tooltip-container"><span class="tooltip"><span><?php echo $_option["label"] ?></span></span></span>
                                            <?php
                                            break;
                                        case 'label':
                                            ?>
                                            <a class="" title="<?php echo $_option["label"] ?>" data-original-title="<?php echo $_option["label"] ?>"   rel="<?php echo $_option["id"] ?>" id="swatches_option_value_<?php echo $_option["id"] ?>" href="#">
                                                <?php echo $_option["label"] ?>
                                            </a>
                                            <?php
                                            break;
                                    }
                                    ?>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
						<?php endif; ?>
                    </div>
                    <?php
                }
                /* Eof MAIN SWATCHES CODE */
                ?>
                <div class="input-box">
                    <select name="super_attribute[<?php echo $_attribute["id"] ?>]" id="attribute<?php echo $_attribute["id"] ?>" class="configurable-option-select required-entry super-attribute-select  swatches-type-<?php echo $_attribute["swatch_type"]; ?> <?php echo (($_attribute["hideselect"]) ? "hideselect" : ""); ?> <?php echo (($_attribute["switchgallery"]) ? "switch-gallery" : ""); ?>">

                    </select>
                </div>
                <div class="clearer">&nbsp;</div>
            </dd>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        function out_of_stock_string() {
            return "<?php echo $this->__(" (Out of Stock)"); ?>";
        }

        var mng_Config = null;
        var spConfig = null;

        jQuery(document).ready(function() {
            window.mng_Config = <?php echo Mage::helper('core')->jsonEncode($_json_config); ?>;
            window.mng_Config.containerId = 'options-container-<?php echo $_product->getId(); ?>';
            window.spConfig = new Product.Config(window.mng_Config);
            window.addNewConfigurableProductMethods();
            window.enableSwatchesOptions("first");
            window.swatchesSelectDefaultValueOnHash();
        });



    </script>
<?php endif; ?>
