<input type="checkbox" class="off-canvas-check" id="off-canvas-left-check">
 
<div id="off-canvas-left" class="off-canvas">
    <div class="main-nav-wrapper">
        <div class="off-canvas-search mobile-search">
            <?php echo $this->getChildHtml('offCanvasSearch') ?>
        </div>
        <div class="off-canvas-categories">
            <?php echo $this->getChildHtml('offCanvasCategories') ?>
        </div>
        <div class="off-canvas-links">
            <?php echo $this->getChildHtml('offCanvasLinks') ?>
        </div>
    </div>
</div>