<?php
	$_product    = $this->getProduct();
	$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl class="product-options-block">
    <?php foreach($_attributes as $_attribute): ?>
        <dt><label class="required"><?php echo $_attribute->getLabel() ?> <em>*</em></label></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box">
                <select <?php if($this->helper('colorswatch')->useIcons()):?>style="display:none;"<?php endif;?> name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                </select>
				<div style="clear:both;"></div>
            </div>
        </dd>
    <?php endforeach; ?>
    </dl>
    
	<script type="text/javascript">
		document.observe('dom:loaded', function() {
			var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>, '', optionsPrice, <?php echo $this->getJsonConfigData() ?>, $('main-image'), $('reload-image-processing'));
		});
	</script>
		
<?php endif;?>
