
<form id="co-billing-form" action="">
<fieldset>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
                <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
        <?php if(!$this->isCustomerLoggedIn()): ?>
                    <div class="field">
                        <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
        <?php endif ?>
                </li>
                <li class="wide">
                    <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
                    </div>
                </li>
        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text" />
                    </div>
                </li>
        <?php endfor ?>
                <li class="fields">
                    <div class="field country-field">
                        <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </div>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="field vat-field">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->htmlEscape($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                    <?php endif; ?>
                    <div class="field city-field">
                        <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" />
                        </div>
                    </div>
                    
                </li>
                <li class="fields">
                    <div class="field zip-field">
                        <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box postcode-field">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field region-field">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li lang="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="billing:telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" />
                        </div>
                    </div>
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                <li class="fields dob-fields">
                <?php if ($_dob->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif; ?>
                <?php if ($_gender->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif ?>
                </li>
            <?php endif ?>

        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
                <li>
                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </li>
        <?php endif ?>
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="fields" id="register-guest">
                    <ul class="form-list">
                        <li class="control">
                            <input onclick="j2t_one_checkout.setMethodCheckbox();" type="checkbox" name="checkout_method_checkbox" id="login:guest_register" value="register"<?php if($this->getQuote()->getCheckoutMethod()!=Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="login:guest"><?php echo $this->__('Create an account for easier access') ?></label>
                        </li>
                    </ul>
                </li>
                <?php endif; ?>
                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" <?php if($this->getQuote()->getPasswordHash()):?>value="<?php echo $this->getQuote()->getCustomer()->decryptPassword($this->getQuote()->getPasswordHash()); ?>" <?php endif;?>id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" <?php if($this->getQuote()->getPasswordHash()):?>value="<?php echo $this->getQuote()->getCustomer()->decryptPassword($this->getQuote()->getPasswordHash()); ?>" <?php endif;?>title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                
                <?php if (Mage::getStoreConfig('j2tonecheckout/default/newsletter_on')): ?>
                <li class="fields j2t-newsletter">
                    <div class="field newsletter-field">
                        <div class="input-box">
                            <input type="checkbox" name="billing[is_subscribed]" id="billing:is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getAddress()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /> 
                            <label for="billing:is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                        </div>
                    </div>
                </li>
                <?php endif ?>
                
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
     </li>
    <?php if ($this->canShip()): ?>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('j2t-onecheckout-shipping').hide(); $('shipping:same_as_billing').checked = true; /*billing.save();*/" class="radio billing_radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></li>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo $this->__('Ship to different address') ?>" onclick="$('j2t-onecheckout-shipping').show(); $('shipping:same_as_billing').checked = false; /*billing.save(); shipping.checkSave();*/" class="radio billing_radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    
    document.observe("dom:loaded", function() {
        if ($('billing:use_for_shipping_no') && $('billing:use_for_shipping_yes')){
            if ($('billing:use_for_shipping_yes').checked){
                $('shipping:same_as_billing').checked = true;
                $('j2t-onecheckout-shipping').hide();
            } else {
                $('shipping:same_as_billing').checked = false;
                $('j2t-onecheckout-shipping').show();
            }
        } else {
            $('j2t-onecheckout-shipping').hide();
            $('checkout-shipping-method-load').hide();
            $('shipping-not-relevant').show();
        }
        j2t_one_checkout.setMethodCheckbox();
    });
    var billing = new J2t_Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/shippingmethod', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('j2tonecheckout/onepage/paymentmethod', array('form_key' => Mage::getSingleton('core/session')->getFormKey()));?>', '<?php echo $this->getUrl('j2tonecheckout/onepage/review', array('form_key' => Mage::getSingleton('core/session')->getFormKey()));?>');
    var billingForm = new VarienForm('co-billing-form');

    $$('#co-billing-form input').invoke('observe', 'click', function (event){
        el = event.element();
        if (el.type == 'radio'){
            if (el.id == "billing:use_for_shipping_yes" && el.id == "billing:use_for_shipping_no"){
                
            }
            j2t_one_checkout.processShippingSelection();
        }
    });
    
    $$('#co-billing-form select').invoke('observe', 'change', function (event){
        el = event.element();        
        if (el.id == 'billing-address-select' || el.id == 'billing:country_id'){
            j2t_one_checkout.processShippingSelection();
        }        
    });
    
    
    Event.simulate = function(element, eventName) {
  
        var options = Object.extend({
          pointerX: 0,
          pointerY: 0,
          button: 0,
          ctrlKey: false,
          altKey: false,
          shiftKey: false,
          metaKey: false,
          bubbles: true,
          cancelable: true
        }, arguments[2] || { } );

        var eventMatchers = {
          'HTMLEvents': /load|unload|abort|error|select|change|submit|reset|focus|blur|resize|scroll/,
          'MouseEvents': /click|mousedown|mouseup|mouseover|mousemove|mouseout/
        };

        var oEvent, eventType = null;

        for (var name in eventMatchers) {
          if (eventMatchers[name].test(eventName)) eventType = name;
        }

        if (!eventType) throw new SyntaxError('Only HTMLEvents and MouseEvents interfaces are supported');

        if (document.createEvent) {
          oEvent = document.createEvent(eventType);
          if (eventType == 'HTMLEvents') {
            oEvent.initEvent(eventName, options.bubbles, options.cancelable);
          }
          else {
            oEvent.initMouseEvent(eventName, options.bubbles, options.cancelable, document.defaultView, 
              options.button, options.pointerX, options.pointerY, options.pointerX, options.pointerY,
              options.ctrlKey, options.altKey, options.shiftKey, options.metaKey, options.button, $(element));
          }
          $(element).dispatchEvent(oEvent);
        }
        else {
          options.clientX = options.pointerX;
          options.clientY = options.pointerY;
          oEvent = Object.extend(document.createEventObject(), options);
          $(element).fireEvent('on' + eventName, oEvent);
        }
      }
    
    /* Un-comment this when postcode and region id is required */
    <?php if (Mage::getStoreConfig('j2tonecheckout/default/reload_townregion') == 1): ?>
    $$('#co-billing-form input, #co-billing-form select').invoke('observe', 'change', function (event){
        el = event.element();        
        if (el.id == 'billing:postcode' || el.id == 'billing:region_id' || el.id == 'billing:region'){//} || el.id == 'billing:city'){
            j2t_one_checkout.processShippingSelection();
        }      
    });
    
    <?php endif;?>
    
    
    
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    document.observe("dom:loaded", function() {
        j2t_one_checkout.processShippingSelection();
        
        var j2tonecheckout = setInterval(function(){
            j2t_one_checkout.checkOverlay();
        },500);
    });


//]]>
</script>
