<script type="text/javascript">
    //<![CDATA[
    
    function showJ2tOneLogin(){
        if ($('j2t-login-cart').style.display == 'none'){
            new Effect.BlindDown('j2t-login-cart'); 
            $('j2t-register-cart').hide(); 
            $('j2t-onecheckout-billing').hide();
            $('j2t-onecheckout-shipping').hide();
            $('or-j2t-guest-checkout-title').show();
            $('j2t-guest-checkout-title').show();
        }
    }
    
    function guestRegisterJ2tOneCheckout(){
        if ($('j2t-register-cart').style.display == 'none'){
            $('j2t-login-cart').hide(); 
            new Effect.BlindDown('j2t-register-cart'); 
            new Effect.BlindDown('j2t-onecheckout-billing'); 
            if($('billing:use_for_shipping_no').checked){
                $('j2t-onecheckout-shipping').show();
            }
            $('or-j2t-guest-checkout-title').hide();
            $('j2t-guest-checkout-title').hide();
        }
        
    }
    //]]>
</script>

<div class="col2-set j2t-login-onecheckout">
    <?php echo $this->getChildHtml('login_before')?>
    <h4><a href="javascript:javascript:showJ2tOneLogin(); void(0);"><?php echo $this->__('Already registered?') ?> <?php echo $this->__('Log In') ?></a></h4>

    <div class="col-1" style="display:none;" id="j2t-login-cart">
        <h3><?php echo $this->__('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <p><?php echo $this->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
        </form>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
            <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
    </div>

    <h4 id="or-j2t-guest-checkout-title" style="display:none;"><?php echo $this->__('Or');?></h4>

    <h4 id="j2t-guest-checkout-title" style="display:none;"><a href="javascript:guestRegisterJ2tOneCheckout(); void(0);"><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></a></h4>
    <div class="col-2" id="j2t-register-cart">
        <?php if (Mage::getStoreConfig('j2tonecheckout/default/show_extra')): ?>
            <div id="j2t-onecheckout-extra-register">
	        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <!--<p><?php echo $this->__('Register with us for future convenience:') ?></p>-->
            	<?php else: ?>
                    <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
                    <?php echo $this->__('Register with us for future convenience:') ?></p>
                    <ul>
                        <li><?php echo $this->__('Fast and easy check out') ?></li>
                        <li><?php echo $this->__('Easy access to your order history and status') ?></li>
                    </ul>
                <?php endif; ?>
       	    </div> 
	<?php endif;?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control" style="display:none;">
                    <input onclick="j2t_one_checkout.setMethod();" type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control" style="display:none;">
                    <input onclick="j2t_one_checkout.setMethod();" type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
            </ul>
            <?php if (Mage::getStoreConfig('j2tonecheckout/default/show_extra')): ?>
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul class="ul">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
            <?php endif;?>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>

        

    </div>
</div>


<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }

    document.observe("dom:loaded", function() {
        var j2t_check_guest = false;
        var j2t_onechekout_guest_inputs = $$('#j2t-register-cart input[type=radio]');
        j2t_onechekout_guest_inputs.each(function (el, index){
            if (el.checked){
                j2t_check_guest = true;
            }
        });

        if (!j2t_check_guest && j2t_onechekout_guest_inputs.length > 0){
            j2t_onechekout_guest_inputs[0].checked = true;
        }
        j2t_one_checkout.setMethod();
    });
//]]>
</script>

